### PR TITLE
When log in, do not use only email.

### PR DESCRIPTION
**Pull request by kappaseijin**
Hi! I'm using Flat every day.

I would like to log in with a string others than email.
Now, using here: (i think)

https://atproto.com/lexicons/com-atproto-session#comatprotosessioncreate
https://github.com/bluesky-social/atproto/blob/main/lexicons/com/atproto/session/create.json

In fact, we can log in with no problem even if `<input type="email">` to `<input type="text">`.
As you probably already know, when sign in, can use a email, custom domain and did.
This PR's priority is very lower.

Best regards.

### CODE REVIEW

**Comment by sabigara** [comment]
Thank you for opening the issue!

Can you make some changes to the input field before merging it?

- label: `Identifier (handle or email)`
- placeholder: `you.bsky.social`

**Comment by sabigara** [comment]
And the `name` should be `identifier` I think

**Comment by kappaseijin** [comment]
OK. I'll try.

**Comment by kappaseijin** [comment]
Done. But my npm's environment is now broken.
```shell
$ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:@types/@atproto/uri

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kappa/.npm/_logs/2023-03-10T11_05_49_919Z-debug-0.log
```

I don't understand.
The file attached. please wait.

**Comment by sabigara** [comment]
You should use [pnpm](https://pnpm.io) for the package manager instead of npm.

**Comment by sabigara** [comment]
lock file is here: https://github.com/sabigara/flat/blob/main/pnpm-lock.yaml

**Comment by kappaseijin** [comment]
Nice! i'll try.

**Comment by kappaseijin** [comment]
Done. Script is all right.
And log in(& out) is success.
Thanks teach me for pnpm.

**Comment by sabigara** [comment]
Thank you for your contribution! I hope you will contribute to solving other issues as well.

**Pull request merged**
